version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: fiapg9
      POSTGRES_USER: fiapg9
      POSTGRES_DB: minha-saude

  minhasaudepi:
    build: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      APP_PROFILE: dev